### ISSUE TITLE
当 hexo deploy 命令报 hexo Permission denied (publickey) 错误解决办法。

### ISSUE THREAD

**Issue by huoyixin** [huoyixin/huoyixin.github.io#1]
网上大多数建议将git版本降低至 `1.9` 或者删除 bolg 目录下的 `.deploy_git` 文件。

我们可以先检查一下`hexo`的`_config.yml`文件中的`git`设置，  `repository` 属性的设置是不是使用的
`ssh://github.com` 可以尝试换成 `git@github.com:huoyixin/huoyixin.github.io.git`

Before：
```
deploy:
  type: git
  repository: ssh://github.com/huoyixin/huoyixin.github.io.git
  branch: master
```

After：
```
deploy:
  type: git
  repository: git@github.com:huoyixin/huoyixin.github.io.git
  branch: master
```
